# Generated by Django 3.2.15 on 2023-11-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderelements_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Необработанный'), ('Preparing', 'Готовится'), ('Delivered', 'Доставляется'), ('Completed', 'Выполнен')], db_index=True, default='Unprocessed', max_length=100, verbose_name='Статус заказа'),
        ),
    ]
