# Generated by Django 3.2.15 on 2023-11-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20231114_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('In cash', 'Наличностью'), ('Electronically', 'Электронно')], db_index=True, default='', max_length=100, verbose_name='Способ оплаты'),
        ),
    ]
